---
deployment:
  tasks:
    - /bin/cp -R /home/beatfyap/public_html/beasworld_repo/* /home/beatfyap/public_html/
    - /bin/cp -R /home/beatfyap/public_html/beasworld_repo/grimoire-of-unfinished-thangs /home/beatfyap/public_html/
